# coding: utf-8

"""
    127.0.0.1:9000

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.4.3+2c41897
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.searchuniversalrelative_api import SearchuniversalrelativeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchuniversalrelativeApi(unittest.TestCase):
    """SearchuniversalrelativeApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.searchuniversalrelative_api.SearchuniversalrelativeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_export_search_relative_chunked(self):
        """Test case for export_search_relative_chunked

        Export message search with relative timerange.  # noqa: E501
        """
        pass

    def test_field_histogram_relative(self):
        """Test case for field_histogram_relative

        Field value histogram of a query using a relative timerange.  # noqa: E501
        """
        pass

    def test_histogram_relative(self):
        """Test case for histogram_relative

        Datetime histogram of a query using a relative timerange.  # noqa: E501
        """
        pass

    def test_search_relative(self):
        """Test case for search_relative

        Message search with relative timerange.  # noqa: E501
        """
        pass

    def test_stats_relative(self):
        """Test case for stats_relative

        Field statistics for a query using a relative timerange.  # noqa: E501
        """
        pass

    def test_terms_histogram_relative(self):
        """Test case for terms_histogram_relative

        Most common field terms of a query over time using a relative timerange.  # noqa: E501
        """
        pass

    def test_terms_relative(self):
        """Test case for terms_relative

        Most common field terms of a query using a relative timerange.  # noqa: E501
        """
        pass

    def test_terms_stats_relative(self):
        """Test case for terms_stats_relative

        Ordered field terms of a query computed on another field using a relative timerange.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
