# coding: utf-8

"""
    127.0.0.1:9000

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.4.3+2c41897
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.searchuniversalabsolute_api import SearchuniversalabsoluteApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchuniversalabsoluteApi(unittest.TestCase):
    """SearchuniversalabsoluteApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.searchuniversalabsolute_api.SearchuniversalabsoluteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_export_search_absolute_chunked(self):
        """Test case for export_search_absolute_chunked

        Export message search with absolute timerange.  # noqa: E501
        """
        pass

    def test_field_histogram_absolute(self):
        """Test case for field_histogram_absolute

        Field value histogram of a query using an absolute timerange.  # noqa: E501
        """
        pass

    def test_histogram_absolute(self):
        """Test case for histogram_absolute

        Datetime histogram of a query using an absolute timerange.  # noqa: E501
        """
        pass

    def test_search_absolute(self):
        """Test case for search_absolute

        Message search with absolute timerange.  # noqa: E501
        """
        pass

    def test_stats_absolute(self):
        """Test case for stats_absolute

        Field statistics for a query using an absolute timerange.  # noqa: E501
        """
        pass

    def test_terms_absolute(self):
        """Test case for terms_absolute

        Most common field terms of a query using an absolute timerange.  # noqa: E501
        """
        pass

    def test_terms_histogram_absolute(self):
        """Test case for terms_histogram_absolute

        Most common field terms of a query over time using an absolute timerange.  # noqa: E501
        """
        pass

    def test_terms_stats_absolute(self):
        """Test case for terms_stats_absolute

        Ordered field terms of a query computed on another field using an absolute timerange.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
