# coding: utf-8

"""
    127.0.0.1:9000

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.4.3+2c41897
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SearchResponseDecorationStats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'added_fields': 'list[str]',
        'changed_fields': 'list[str]',
        'removed_fields': 'list[str]'
    }

    attribute_map = {
        'added_fields': 'added_fields',
        'changed_fields': 'changed_fields',
        'removed_fields': 'removed_fields'
    }

    def __init__(self, added_fields=None, changed_fields=None, removed_fields=None):  # noqa: E501
        """SearchResponseDecorationStats - a model defined in Swagger"""  # noqa: E501

        self._added_fields = None
        self._changed_fields = None
        self._removed_fields = None
        self.discriminator = None

        if added_fields is not None:
            self.added_fields = added_fields
        if changed_fields is not None:
            self.changed_fields = changed_fields
        if removed_fields is not None:
            self.removed_fields = removed_fields

    @property
    def added_fields(self):
        """Gets the added_fields of this SearchResponseDecorationStats.  # noqa: E501


        :return: The added_fields of this SearchResponseDecorationStats.  # noqa: E501
        :rtype: list[str]
        """
        return self._added_fields

    @added_fields.setter
    def added_fields(self, added_fields):
        """Sets the added_fields of this SearchResponseDecorationStats.


        :param added_fields: The added_fields of this SearchResponseDecorationStats.  # noqa: E501
        :type: list[str]
        """

        self._added_fields = added_fields

    @property
    def changed_fields(self):
        """Gets the changed_fields of this SearchResponseDecorationStats.  # noqa: E501


        :return: The changed_fields of this SearchResponseDecorationStats.  # noqa: E501
        :rtype: list[str]
        """
        return self._changed_fields

    @changed_fields.setter
    def changed_fields(self, changed_fields):
        """Sets the changed_fields of this SearchResponseDecorationStats.


        :param changed_fields: The changed_fields of this SearchResponseDecorationStats.  # noqa: E501
        :type: list[str]
        """

        self._changed_fields = changed_fields

    @property
    def removed_fields(self):
        """Gets the removed_fields of this SearchResponseDecorationStats.  # noqa: E501


        :return: The removed_fields of this SearchResponseDecorationStats.  # noqa: E501
        :rtype: list[str]
        """
        return self._removed_fields

    @removed_fields.setter
    def removed_fields(self, removed_fields):
        """Sets the removed_fields of this SearchResponseDecorationStats.


        :param removed_fields: The removed_fields of this SearchResponseDecorationStats.  # noqa: E501
        :type: list[str]
        """

        self._removed_fields = removed_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchResponseDecorationStats, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchResponseDecorationStats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
